version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vbs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    ports:
      - "5173:80"

volumes:
  mongo_data: